### ISSUE TITLE
Manifest must be first entry in JAR

### ISSUE THREAD

**Issue by lefou** [Zlika/reproducible-build-maven-plugin#16]
The produced JAR is not always specification conform. According to the spec, the manifest entry must be the first entry of the JAR file.

Currently, if there are entries in the JAR with a name which is alphabetically before the "META-INF/MANIFEST.MF" entry e.g. "Changelog.txt", they will be inserted before the JAR Manifest. 

If the `MANIFEST.MF` is not the first entry, reading the MANIFEST via the `java.util.jar.JarInputStream#getManifest()` will return `null`.

**Comment by Zlika** [comment]
Can you point me where the JAR specification says that? After a little Googling I found at https://stackoverflow.com/questions/4727637/how-do-i-verify-the-order-of-manifest-mf-within-jar the following answer:

> Actually the specification does NOT say that they must be first. However the jar command line tool does place them first and some tools expect them to be, for example because a tool could quickly scan the manifests from an entire directory of JAR files. So it's really more of a convention than a requirement.

Other comments say that the META-INF folder must be first, then the META-INF/MANIFEST.MF file should be in 2nd position.
Another comment says that IntelliJ put WEB-INF before META-INF when creating a WAR file.
So I do not know what I have to do precisely to comply to other tools that wants to read the MANIFEST file.

**Comment by lefou** [comment]
I agree, the fact that the MANIFEST "must" come first (or second, after "META-INF") isn't spec'ed in text. I believed I read it some years ago, but can't find any source for it anymore. _But_ it is essentially spec'ed in code, at least in Oracle-code, and almost any Java tool will treat your JAR without a `META-INF/MANIFEST.MF` in first (or second) position like a JAR without a manifest.
All OSGi tools and containers I know also will fail.

For the quasi-spec in code, please see this comment from `java.util.jar.JarInputStream`:

>        // This implementation assumes the META-INF/MANIFEST.MF entry
>        // should be either the first or the second entry (when preceded
>        // by the dir META-INF/). It skips the META-INF/ and then
>        // "consumes" the MANIFEST.MF to initialize the Manifest object.

**Comment by lefou** [comment]
IMHO, the plugin should not "decide" the best position when it finds more first-position candidates like e.g. a `web.xml`. But It should either go with the choice of the original JAR or use a configuration property for it.

Moving a first-position manifest away isn't a proper default-treatment.

**Comment by Zlika** [comment]
From the jar tool manual:

> The jar tool automatically generates a manifest file entry named META-INF/MANIFEST.MF. It is always the first entry in the jar file. 

However, I can see in the JAR files I have in my local maven repo that some starts with META/INF-MANIFEST.MF and then META-INF/, and others do the opposite. In any case, other files in the META-INF folder seem to be put in a random order in the JAR file.
I agree that I could change the file sorting to put these 2 entries first, but which order would be the best according to you?

**Comment by lefou** [comment]
For the rest I suggest to sort them alphabetically. For less clutter, it might be wise to keep the whole META-INF at the beginning, but that's only a vague guess.

The benefit of having the `META-INF/MANIFEST.MF` in the beginning, even before `META-INF/` is, that tools like `zless` can simply uncompress the head of the file to see the manifest. I use this convenience regularly.

I never came across ZIP tools, that couldn't handle those file-entry-before-folder-entry situations.

**Comment by Zlika** [comment]
I changed the file order in ZIP files to start with META-INF/ and META-INF/MANIFEST.MF. I prefered this order over META-INF/MANIFEST.MF and then META-INF/ because this is already the order found in JAR files produced by maven-jar-plugin, so I expect less potential problems with it. Can you check if it is ok for you?

**Comment by lefou** [comment]
As I told you, there are no known issues whether META-INF/MANIFEST.MF or META-INF/ comes first. The JAR tool and als Apache Ant place META-INF/ first.
I will probably check tomorrow.

**Comment by lefou** [comment]
Your fix works in the sense that the manifest is now recognized by tools and the `JarInputStream` as such.

But I advice to keep all `META-INF/*` entries after that close together for the following reasons:
* Keeping all content of a "directory" together is easier to recognize, reason about and debug
* Some performance related files are inside `META-INF`, e.g. `META-INF/INDEX.LIST`, also the `WEB.XML` you mentioned earlier. Placing them before any other (class) file might be more performant.

And if I can make a wish: Can you please position the `META-INF/MANIFEST.MF` before the `META-INF`. It makes the daily work with JARs on the command line so much more pleasant.

**Comment by Zlika** [comment]
I don't think there is any performance benefits depending on the location of the file in the ZIP, because there is a direct access of any file from the Central Directory at the end of the ZIP file (there is no need to unpack the first files to access the following ones, contrary to the tar.gz format). I analyzed several third party JAR/WAR files, and files in META-INF and WEB-INF directories are scattered in a random order inside the JAR file. So there is no reason to do something clever here.

If it REALLY pleases you I will make the MANIFEST file first, even if it somehow disturbs me to put a file before its folder. :-)
