### ISSUE TITLE
Support jenkins plugin .hpi

### ISSUE THREAD

**Issue by lanlingxueyu** [Zlika/reproducible-build-maven-plugin#27]
Hello
      Please support jenkins plugin .hpi package difference elimination
      1.MANIFEST.MF
      2.pom.properties
      3. *.stapler
       #Fri Sep 28 09:38:28 GMT+08:00 2018

thank you very much

**Comment by Zlika** [comment]
Hi @lanlingxueyu,
I downloaded and extracted a Jenkins plugin to analyse it, but I cannot see any *.stapler file. Can you tell me what are these files and where I can found one?
Regards
