### ISSUE TITLE
Feature Request:  Set line endings in text files

### ISSUE THREAD

**Issue by aharui** [Zlika/reproducible-build-maven-plugin#37]
The javax.inject.Named annotation adds a newline into a generated text file that ends up in the META-INF of a jar.  The newline is 0x0D 0x0A on Windows and 0x0A on Mac.

Snippets of code from: [https://github.com/apache/royale-compiler/blob/develop/royale-maven-plugin/src/main/java/org/apache/royale/maven/trust/DefaultTrustHandler.java](https://github.com/apache/royale-compiler/blob/develop/royale-maven-plugin/src/main/java/org/apache/royale/maven/trust/DefaultTrustHandler.java)

```
import  javax.inject.Named;
@Named
public class DefaultTrustHandler {
}
```

Results in:
META-INF/sisu/javax.inject.Named

Which has different newlines on Windows vs Mac

**Comment by Zlika** [comment]
Thank you for reporting this issue.
I don't want to blindly enforce line endings because I'm not sure a text file detection algorithm would be 100% bullet proof, and their may be some text files that must have a particular line ending to work.
However, here we have a precise file and changing its line endings should not break the JAR. So I will only change the line endings of this particular file. Do you know other dependency injection frameworks that would also generate text files with platform dependent line endings?

**Comment by aharui** [comment]
Thanks for responding.  I don't know about other DI frameworks or other tools.  I was thinking this plugin could just have a new goal or configuration property like "set-line-endings" and you provide a list of files or something like that.  I'd be totally fine with having to explicitly list what files to fix instead of the plugin making assumptions.

**Comment by Zlika** [comment]
Hi!
The plugin now automatically changes the line endings of META-INF/sisu/javax.inject.Named. It also allows to specify a list of text files where it should also make the line endings reproducible. I was not very inspired to name this new configuration option, it is called "newLineTextFiles". If you have a better idea please let me know.
Could you please compile a SNAPSHOT version of the plugin and test it on your project to check that it correctly fixes your problem?
Thanks.

**Comment by aharui** [comment]
OK, I will try a SNAPSHOT.  It might be a few weeks before I get to it.  Or it might be this weekend, not sure.

**Comment by aharui** [comment]
I did find time and it appears to be working, so thank you for your quick response.  How soon can you make a non-SNAPSHOT release?  We want to release soon and having an official release would be helpful.

**Comment by Zlika** [comment]
Ok, I'll do it this weekend.

**Comment by Zlika** [comment]
Released!

**Comment by aharui** [comment]
Thank you so much!  It appears to be working.
