### ISSUE TITLE
version v0.9 cannot make jar file reproducible

### ISSUE THREAD

**Issue by hybnew** [Zlika/reproducible-build-maven-plugin#39]
As title, i spent a lot time to test v0.9  ,finally it turns out this version cannot make maven package reproducible.but any of other can .

**Comment by Zlika** [comment]
Hi.
Can you give a sample project that would reproduce the problem?

**Comment by hybnew** [comment]
So wired ... new project cannot reproduce that , may be my maven submodule and dependencies problem,i'll check this tomorrow and see if close .
