### ISSUE TITLE
Support for tar.gz tar.bz archives

### ISSUE THREAD

**Issue by tglman** [Zlika/reproducible-build-maven-plugin#4]
Hi,

Would be cool to add the support of stripping dates also from tar.gz tar.bz archives that are often generated in maven build with assembly plugin.

This can be easily achieved building a Stripper using [TarArchiveEntry](https://commons.apache.org/proper/commons-compress/javadocs/api-1.14/org/apache/commons/compress/archivers/tar/TarArchiveEntry.html)

Bye

**Comment by Zlika** [comment]
Hi,

That's a good idea, but I don't have time to work on it right now, so you can propose a PR if you want.

**Comment by tglman** [comment]
hi @Zlika,

What is the code formatter did you use ? I'm using eclipse, and I'm a step ahead on the PR, but I would prefer to use your code formatter for coherence, as well what are the field that should be stripped in the tar ?

some hint on the WIP https://gist.github.com/tglman/520e6c04f407ef07d8a3a6b290d3c20d

Regards
