### ISSUE TITLE
Support multiproject

### ISSUE THREAD

**Issue by weltonrodrigo** [Zlika/reproducible-build-maven-plugin#40]
Right know when building a project with subprojects, the strip-jar goal is skipped.

**Comment by Zlika** [comment]
Hi,
Thanks for reporting this issue. Could you give me a sample project that reproduces the problem? Because the last time I used it on a multi module project it worked.

**Comment by Zlika** [comment]
I've just checked on a multi-module project and it works ok. Please check the usage page of the plugin: http://zlika.github.io/reproducible-build-maven-plugin/usage.html

**Comment by weltonrodrigo** [comment]
It works if you set it per-project. Is there a way to set it on parent POM?

Besides, when running the goal via CLI, the sub-modules are not stripped.

**Comment by Zlika** [comment]
I tested it on a multi-module project by adding it only in the parent pom, and it stripped the child modules without problem. Could you give me a sample project reproducing your problem?
