### ISSUE TITLE
file name is too long ( > 100 bytes)

### ISSUE THREAD

**Issue by fasidOnGit** [Zlika/reproducible-build-maven-plugin#44]
Is there a way to increase the limit? 
My file named is not really long... but because it's nested deep into the folders hence it's complaining to be lengthy file name. 
``` 
Execution default of goal io.github.zlika:reproducible-build-maven-plugin:0.5.2:strip-jar failed: file name 'nested/folder/path/fileName.extension' is too long ( > 100 bytes)
```

Thanks :)

**Comment by Zlika** [comment]
Hi!
I cannot find this error message in the code of this plugin, so it's maybe from one of its dependencies, but it's difficult to debug without additional info: could you copy/paste the log you have when running maven with -e -X ?

**Comment by fasidOnGit** [comment]
@Zlika I have almost no experience in this area.
 Does this help you?
https://stackoverflow.com/questions/32528799/when-i-tar-a-file-its-throw-exception-as-is-too-long-100-bytes-tararchiveo/34611985#34611985

https://github.com/Zlika/reproducible-build-maven-plugin/blob/master/src/main/java/io/github/zlika/reproducible/TarStripper.java#L83

**Comment by Zlika** [comment]
Thanks for the pointer. I think I fixed with the bug with the latest commit. Can you try to compile the latest snapshot version of this plugin and test it on your project to check the fix? If it is ok I will release a new version of the plugin.

**Comment by fasidOnGit** [comment]
@Zlika A new release would be great I guess :) right now We have other problems with the build so hence disabling the plugin for now... :) 
I appreciate your quick response

**Comment by Zlika** [comment]
@fasidOnGit I'm releasing version 0.12. It should be available soon on Maven Central.
