### ISSUE TITLE
war packaging with embedded jar file

### ISSUE THREAD

**Issue by heribender** [Zlika/reproducible-build-maven-plugin#45]
Your plugin does not produce identical artifacts on my multi-module project, where one sub-module has the packaging "war" defined.  This sub-module also has code, it first assembles a jar, but not in the target root folder, but in target\eas-admin-4.0-SNAPSHOT\WEB-INF\lib\eas-admin-4.0-SNAPSHOT.jar.

Running "mvn clean install -DskipTests" shows on console:

 --- maven-war-plugin:3.3.0:war (default-war) @ eas-admin ---
[INFO] Packaging webapp
[INFO] Assembling webapp [eas-admin] in [C:\Development\eascs2.0\trunk\eas-admin\target\eas-admin-4.0-SNAPSHOT]
[INFO] Processing war project
[INFO] Copying webapp webResources [C:\Development\eascs2.0\trunk\eas-admin\src/main/resources/int] to [C:\Development\eascs2.0\trunk\eas-admin\target\eas-admin-4.0-SNAPSHOT]
...
[INFO] Building jar: C:\Development\eascs2.0\trunk\eas-admin\target\eas-admin-4.0-SNAPSHOT\WEB-INF\lib\eas-admin-4.0-SNAPSHOT.jar
[INFO] Building war: C:\Development\eascs2.0\trunk\eas-admin\target\EasAdminService.war
[INFO]
[INFO] --- reproducible-build-maven-plugin:0.12:strip-jar (default) @ eas-admin ---
[INFO] Stripping C:\Development\eascs2.0\trunk\eas-admin\target\EasAdminService.war

As you see, only the generated war file is stripped by your plugin, but not embedded jar file. Comparing two builds indeed shows that the jar files does not produce the same hash, and therefore neither the stripped war.

Is there a workaround to strip also the jar file of this sub-module?

**Comment by Zlika** [comment]
Hi!
Is the jar file created in the same phase/goal of the maven-war-plugin then the war file?

**Comment by heribender** [comment]
It seems so. I am not very good in these maven phase/goal stuff. The log output (see previous post) is done by the maven-war-plugin, just before your plugin comes into action.  The two lines "Building jar ..." and "Building war..." occur directly together.

My pom files do not define a phase/goal in the war-plugin. It just contains some resource-copy definitions to the target folder \target\eas-admin-4.0-SNAPSHOT, which seems to be the blueprint for the war packaging.

**Comment by heribender** [comment]
BTW: used versions:
maven: 3.6.3
war-plugin: 3.3.0
reproducible-build-maven-plugin: 1.2
jdk1.8.0_u231-x64

**Comment by Zlika** [comment]
Can you share the configuration of the maven-war-plugin? I use it in one of my projects but it doesn't create an intermediate jar file, it directly puts class files in the war.

**Comment by heribender** [comment]
Sorry for late answer. Had a lot of other urgent things to do.

From parent pom:

                    <plugin>
                        <artifactId>maven-war-plugin</artifactId>
                        <configuration>
                            <archiveClasses>true</archiveClasses>
                        </configuration>
                    </plugin>

Sub-Module:

                    <plugin>
                        <artifactId>maven-war-plugin</artifactId>
                        <configuration>
                            <warName>EasAdminService</warName>
                            <packagingExcludes>
                                WEB-INF/lib/eas-cs*.jar
                            </packagingExcludes>
                            <webResources>
                                <resource>
                                    <directory>${project.build.testOutputDirectory}</directory>
                                    <targetPath>WEB-INF/classes</targetPath>
                                    <includes>
                                        <include>easAdminProperties.xml</include>
                                    </includes>
                                </resource>

                                ... (more resource elements)

                            </webResources>
                        </configuration>
                    </plugin>

The "culprit" seems to be the "<archiveClasses>true</archiveClasses>" directive. See http://maven.apache.org/plugins/maven-war-plugin/faq.html.

Hope this helps. And thanks for your responsivness!

**Comment by Zlika** [comment]
Hi!
The only quick workaround I see is to remove the "archiveClasses" tag. Is it really needed?
As the JAR and the WAR are produced during the same phase, reproducible-build-maven-plugin cannot be configured to strip the JAR after it is created and before the WAR is created.
Another solution is to use recent versions of the maven plugins, because they can now produce reproducible artifacts (cf. https://maven.apache.org/guides/mini/guide-reproducible-builds.html).

**Comment by heribender** [comment]
Thanks for your advice.
Removing the "archiveClasses" tag was not enough, but explicitely setting it to false did the trick. Now no jar is built anymore in the war module, and the stripped war produces always the same hash when building on the same SVN-Revision.

**Comment by Zlika** [comment]
Glad to know we were able to workaround this problem.
