### ISSUE TITLE
Spring Boot spring.factories causing unreproducible builds

### ISSUE THREAD

**Issue by arobie1992** [Zlika/reproducible-build-maven-plugin#54]
This seems to be very similar to this issue: https://github.com/Zlika/reproducible-build-maven-plugin/issues/41

When using the Maven shade plugin and Spring Boot version 2.4.7, I'm getting unreproducible builds. After looking in diffoscope, it seems to be due to a timestamp that's being included in the META-INF/spring.factories file.

    #Merged by PropertiesMergingResourceTransformer
    #Thu Dec 16 11:23:36 EST 2021
    ...

I saw in the other PR that you added a couple checks for build-info.properties and git.properties to strip comments. If you think the same approach is reasonable here, I can try putting together a PR to address this file as well.

**Comment by Zlika** [comment]
Thank you for reporting this issue. Feel free to propose a PR.

**Comment by arobie1992** [comment]
Here's the PR: https://github.com/Zlika/reproducible-build-maven-plugin/pull/55/files

Tested with a local maven installation and it seems to work. Let me know how that looks.

**Comment by Zlika** [comment]
Fixed by PR #55.

**Comment by arobie1992** [comment]
Is there an ETA for when the next version will be in Maven central?

**Comment by Zlika** [comment]
I've just pushed a new release, so it should be available in Central in the coming minutes/hours.
